version: "3.8"

services:
  homebridge:
    image: homebridge/homebridge:latest
    container_name: homebridge
    restart: unless-stopped
    network_mode: host
    volumes:
      - ~/nas-gateway-data/homebridge:/homebridge

  nas-gateway:
    build: ./gateway
    container_name: nas-gateway
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    
  wol-server:
    image: secretkr/wol-server:latest
    container_name: wol-server
    restart: unless-stopped
    network_mode: host
    volumes:
      - ~/nas-gateway-data/wol-server:/app/data